import jsPDF from "jspdf";

function FinancialReport() {

  const downloadPDF = () => {

    const doc = new jsPDF();

    doc.setFontSize(18);
    doc.text("BudgetWise Financial Report", 20, 20);

    doc.setFontSize(12);
    doc.text("Summary:", 20, 40);

    doc.text("• Income and Expense tracked successfully", 20, 50);
    doc.text("• AI-based prediction included", 20, 60);
    doc.text("• Smart suggestions generated", 20, 70);

    doc.text("Generated by BudgetWise AI System", 20, 100);

    doc.save("BudgetWise_Report.pdf");
  };

  return (
    <div style={{ padding: "20px" }}>
      <h2>📄 Financial Report</h2>

      <button onClick={downloadPDF}>
        Download PDF
      </button>
    </div>
  );
}

export default FinancialReport;