server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/budgetwisedb
spring.datasource.username=budgetwise
spring.datasource.password=Work@03

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true